Repository Finance-Partner/MOAYO-Front, pull requests merged in 2024-06, with the labels that each got.

#28 (#15)예산 페이지 수정
  src/components/home/Budget.tsx
  src/components/home/HouseHolder.tsx
  src/components/home/dashboard/DonutChart.tsx
Labels: ✏️Feature

#30 (#29)고정 수입/지출 구현, 지출 CRUD페이지 작성
  src/components/home/Budget.tsx
  src/components/home/calendar/Detail.tsx
  src/components/home/dashboard/FixExpense.tsx
  src/components/home/dashboard/FixIncome.tsx
Labels: ✏️Feature

#32 (#31)달력 수입/지출 내역 표시
  src/components/home/calendar/Overview.tsx
  src/components/home/calendar/ReactCalendar.tsx
  src/components/home/calendar/types.ts
Labels: ✏️Feature

#34 (#33)가계부 선택 구현 및 유저 정보 표시
  src/atom.ts
  src/components/home/Budget.tsx
  src/components/home/calendar/Detail.tsx
  src/components/home/calendar/Overview.tsx
  src/components/home/calendar/SubmitForm.tsx
  src/components/home/dashboard/CategoryChart.tsx
  src/components/home/dashboard/DashHistory.tsx
  src/components/home/dashboard/DonutChart.tsx
  src/components/home/dashboard/FixExpense.tsx
  src/components/home/dashboard/FixIncome.tsx
  src/components/home/dashboard/MonthExpense.tsx
  src/components/home/dashboard/MonthIncome.tsx
  src/components/home/dashboard/Teammate.tsx
  src/screen/Home.tsx
Labels: 🔧 Refactor, ✏️Feature

#37 (#35) 가계부 생성 기능
  src/atom.ts
  src/screen/Home.tsx
Labels: ✏️Feature

#38 (#36) 유저 프로필 관리 기능
  src/screen/Home.tsx
Labels: ✏️Feature

#40 (#39) 가계부 관리 및 초대 관련 기능 구현
  src/atom.ts
  src/components/Login.tsx
  src/components/Register.tsx
  src/components/home/Budget.tsx
  src/components/home/CreateLedgerForm.tsx
  src/components/home/EditLedgerForm.tsx
  src/components/home/HouseHolder.tsx
  src/components/home/InviteUserForm.tsx
  src/components/home/Modal.tsx
  src/components/home/Navbar.tsx
  src/components/home/ProfileForm.tsx
  src/components/home/calendar/Detail.tsx
  src/components/home/calendar/Overview.tsx
  src/components/home/calendar/SubmitForm.tsx
  src/components/home/dashboard/CategoryChart.tsx
  src/components/home/dashboard/DashHistory.tsx
  src/components/home/dashboard/DonutChart.tsx
  src/components/home/dashboard/FixExpense.tsx
  src/components/home/dashboard/FixIncome.tsx
  src/components/home/dashboard/MonthExpense.tsx
  src/components/home/dashboard/MonthIncome.tsx
  src/components/home/dashboard/Teammate.tsx
  src/img/basicUserImage.png
  src/img/basicUserImg.png
  src/img/moayoLogo.png
  src/img/moayoLogo2.png
  src/screen/Home.tsx
  src/screen/Main.tsx
Labels: ✏️Feature

#42 (#41) 알림 기능 추가
  src/components/home/HouseHolder.tsx
  src/components/home/Modal.tsx
  src/components/home/Navbar.tsx
  src/components/home/Notification.tsx
  src/components/home/calendar/SubmitForm.tsx
  src/screen/Home.tsx
Labels: ✏️Feature

#45 (#43) 가계부 채팅 및 탈퇴 기능 추가
  src/components/home/ChatDropDown.tsx
  src/components/home/HouseHolder.tsx
  src/components/home/Modal.tsx
  src/components/home/Navbar.tsx
  src/img/basicUserImg.png
Labels: ✏️Feature

#48 (#46-47) 가계부 페이지에 고정지출 내역 수정 및 내역 추가 관련 수정
  src/components/home/DashBoard.tsx
  src/components/home/calendar/FixedDetail.tsx
  src/components/home/calendar/Overview.tsx
  src/components/home/calendar/ReactCalendar.tsx
  src/components/home/calendar/SubmitForm.tsx
  src/components/home/dashboard/FixExpense.tsx
  src/components/home/dashboard/Teammate.tsx
  src/img/crownImg.png
  src/img/moreBtn.png
Labels: 🔧 Refactor, ✏️Feature

#50 (#49) 로고 수정
  src/img/moayoLogo2.png
Labels: 🔧 Refactor

#51 (#49) UI 개선
  src/components/home/ChatDropDown.tsx
  src/components/home/CreateLedgerForm.tsx
  src/components/home/DashBoard.tsx
  src/components/home/EditLedgerForm.tsx
  src/components/home/HouseHolder.tsx
  src/components/home/InviteUserForm.tsx
  src/components/home/Modal.tsx
  src/components/home/Notification.tsx
  src/components/home/ProfileForm.tsx
  src/components/home/calendar/Detail.tsx
  src/components/home/calendar/ReactCalendar.tsx
  src/components/home/calendar/SubmitForm.tsx
  src/components/home/dashboard/DashHistory.tsx
  src/screen/Main.tsx
Labels: 🔧 Refactor

#53 (#52)분석 페이지 구현
  package-lock.json
  package.json
  src/components/Root.tsx
  src/components/home/Analysis.tsx
  src/components/home/Budget.tsx
  src/components/home/analysis/AnalysisCategoryChart.tsx
  src/components/home/analysis/Ranking.tsx
  src/components/home/analysis/WordCloud.tsx
Labels: ✏️Feature

#54 (#18)preview페이지 수정
  README.md
  src/img/pre1.png
  src/img/pre2.png
  src/img/pre3.png
  src/screen/Main.tsx
Labels: ✏️Feature

#55 Junyou
  src/components/Login.tsx
  src/components/Register.tsx
  src/components/home/dashboard/DonutChart.tsx
Labels: ✏️Feature

#56 (#52)분석그래프 오류 수정
  src/components/home/Analysis.tsx
Labels: 🔧 Refactor
